FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy your runner script
COPY run.py .

# Execute the script when the container is triggered by the pipeline
CMD ["python", "run.py"]
